version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - belfordz
  - shanejonas
  assignees:
  - belfordz
  ignore:
  - dependency-name: "@open-rpc/meta-schema"
    versions:
    - ">= 1.4.a, < 1.5"
  - dependency-name: "@open-rpc/meta-schema"
    versions:
    - 1.14.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.16.0
    - 4.20.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
